name: Production deployment

on: 
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: cd-with-actions-vliubko
  AZURE_APP_PLAN: actions-ttt-deployment-vliubko
  AZURE_LOCATION: '"Central US"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: vliubko-ttt-app
  #################################################
